### ISSUE TITLE
This was really helpful to me!

### ISSUE THREAD

**Issue by swimclan** [mohammed-bahumaish/deploy-docker-to-remote-server-without-container-registry#1]
Thank you for putting this repo out there.  Not only did I learn more about GitHub Actions but Docker Compose as well!  Kudos 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊

**Comment by mohammed-bahumaish** [comment]
Happy to hear that! 😊
